### ISSUE TITLE
minor edits needed

### ISSUE THREAD

**Issue by stocktons** [rithmschool/rithm-interview-prep-practice-part-2#1]
**countIfHasValue**
test for 7 should equal 5

**findFirstMove**
the starter code has parameters added, but none of the others do - is this on purpose? (assuming no and will remove)

@elie  - this one needs your eyeballs:
**reverseValues**:
to me, this is what the instructions are asking for:
```js
function reverseValues(arr) {
  result = [];
  for(let i = 0; i < arr.length; i++) {
    if( arr[i] % 2 === 1) {
      result.unshift(arr[i]);
    } else {
      i += 2;
    }
  }
  return result;
}

reverseValues([1, 1, 3, 3, 2]) // [3, 3, 1, 1]
reverseValues([1, 3, 5, 7]) // [7, 5, 3, 1]
reverseValues([1, 3, 4, 7]) // [3, 1]
reverseValues([11, 13, 15, 20, 1, 1]) // [15, 13, 11]
reverseValues([4, 5, 1, 1, 2, 1, 1]) // [1]
reverseValues([2, 2, 2]) // []
```

But the provided solutions look like the array is reversed first and then looped through. Which should it be, and how can we clarify the directions?

**robotInstructions**
Do we want to worry about a case of zero of a certain type of move?

**Comment by stocktons** [comment]
updated the instructions for countIfHasValues to be clearer and to match the original solution code and tests, rather than changing them

**Comment by stocktons** [comment]
permission denied when I tried to push my new branch with updates :(

**Comment by elie** [comment]
@stocktons - just gave you write access!

**Comment by stocktons** [comment]
Write access seem to not have gone through, so I forked it and made a PR
from my repo. (First time doing that, so let me know if anything looks
weird!)
